### ISSUE TITLE
[BOT] How about to use a Telegram Bot as reference?

### ISSUE THREAD

**Issue by milesibastos** [Facebook-Hackathon-COVID-AI/covid-ai-fb-hackathon#1]
Hi @xdebbie I got here from your devpost invitation to join.

I built a bot for Telegram that I think would be a good starting point.
https://github.com/milesibastos/covid-19

What do you think?

**Comment by xdebbie** [comment]
Hey @milesibastos! Your bot is really cool! The goal is to create a similar bot on Messenger using Wit.ai so surely your expertise will be valuable! May I add you to the GitHub group? There is a doc file which has the instructions and all the info about the team organised, so you can sign up there. We are also talking on a Slack channel, so I can send you the link for you to join!

**Comment by milesibastos** [comment]
Nice lets rock! Let me in... may u send me the links?
at meantime the telegram bot is also using the Wit.ai to detect location from the message and show local data when u ask for: "Tell me about New York"

![image](https://user-images.githubusercontent.com/55114/82933181-ef140e80-9f5f-11ea-9728-e151919bb0e3.png)

**Comment by xdebbie** [comment]
This is awesome, may I have your e-mail so I can add you to our Slack channel?

**Comment by milesibastos** [comment]
u may use the same from here: antonio@milesibastos.com
